# describe the web and db services that make up the app
version : "3.7"
services:
  flaskweb:
    container_name: "customers-crud-app"
    build: .
    command: python app.py run 0.0.0.0:5000
    ports:
      - 5000:5000
    depends_on:
      - pgdb
  pgdb:
    container_name: "customers-db"
    image: postgres:13
    volumes:
      - db_volume:/var/lib/postgresql/pgdata/
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=customers
    ports: 
      - 5432:5432
volumes:
  db_volume: